### ISSUE TITLE
Animation Bug

### ISSUE THREAD

**Issue by Mooncake911** [Eltaurus-Lt/Anki-Card-Templates#17]
When I don't choose any item and press ENTER, the right word is atomaticly selected. 

![photo_2024-07-04_19-17-53](https://github.com/Eltaurus-Lt/Anki-Card-Templates/assets/90641016/84ea666e-9f01-46ec-94cb-60df0125720e)

**Comment by Mooncake911** [comment]
I'd appreciate it if you could add the ability to select items by keyboard keys: 1, 2, 3, 4...

**Comment by Eltaurus-Lt** [comment]
> When I don't choose any item and press ENTER, the right word is atomaticly selected.

Aren't you confusing being selected with just highlighting the correct answer? This is exactly how it works on Memrise, and is in accordance with pressing a wrong answer as well (either way the answer you should have pressed is highlighted in green).
If you submit an empty answer, after being shown the correct one you should be transitioned to the info screen, providing more details on the question, and when `Enter` is pressed afterwards the card will be autorated as failed instead of good (which you can verify during review by opening `More` → `Previous Card Info` on the next one you see).

---

> I'd appreciate it if you could add the ability to select items by keyboard keys: 1, 2, 3, 4...

This functionality is actually already in the template, but is it not working properly because it is blocked by Anki default shortcuts. I made an update for the Add-on to fix this issue, but have not yet merged it into a full-fledged update. If you'd like to beta-test it, you can download the respective version of the Add-on from this branch:
https://github.com/Eltaurus-Lt/Anki-Card-Templates/tree/2f36e4046e28f95d93d761b518fdfe1f421e4e32

(If you do that, after this version is released, you will probably have to reinstall it back from Ankiweb again to keep receiving automatic updates)

---

on a sidenote, I would appreciate it if you'd make separate threads for different issues, as that makes managing and referencing them so much easier.

**Comment by Mooncake911** [comment]
Thank you master for your answer. I checked again, you were right. I'm probably used to pressing the [I don't know] button.

![image](https://github.com/Eltaurus-Lt/Anki-Card-Templates/assets/90641016/3714a6ac-7782-4528-8256-8e123d1e3628)

**Comment by Mooncake911** [comment]
Thank you master for your answer. I checked again, you were right. I'm probably used to pressing the [I don't know] button.

![image](https://github.com/Eltaurus-Lt/Anki-Card-Templates/assets/90641016/2e132ae1-34c5-4342-ae0a-fe89b479aab9)

**Comment by Eltaurus-Lt** [comment]
The 'I don't know' button seems to function in the same way described above (in fact, the template has this button as well, just keeps it hidden, while pressing enter is attached to it and triggers the same transition to the backside).

(к слову, спасибо за заботливый перевод с русского на английский, но он, в целом, не так необходим 😊)

**Comment by Eltaurus-Lt** [comment]
> I'd appreciate it if you could add the ability to select items by keyboard keys: 1, 2, 3, 4...

With the most recent Add-on version from AnkiWeb, the keys should finally be fully functioning. 

By default the 1, 2, 3, 4 keys are used by Anki to rate cards `Again`, `Hard`, `Good`, and `Easy` respectively, so the addon disables this behavior. The Memrise template will still be able to use these keys for rating a card when they are pressed on the backside, while using them for answer selection in multiple-choice questions when pressed on the frontside. Other Note Types (and older versions of the Memrise template), however, won't be able to use the rating keyboard shortcuts without proper adjustments. If you'd like to revert the functionality of the number keys to their Anki default, it can be done via the Add-on's config at any time.

---

Also, v4.2 the template has a proper dark theme (as well as several other themes):

![image](https://github.com/user-attachments/assets/895948eb-a73c-419f-8906-f78527d938c8)
